name: Deploy PHP/HTML Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy
        run: |
          set -x
          
          # Go to your web directory
          cd /var/www/html/ecom
          
          # Pull latest changes
          git pull origin main
